# THIS FILE IS MEANT TO BE AN EXAMPLE DOCKER COMPOSE FILE TO RUN THE BOT

version: "3.8"

services:
  # Bot service
  inhouse_bot:
    image: mrtolkien/inhouse_bot
    environment:
      # The connection string is an SQLAlchemy connection string, does not need a password since it uses sockets
      INHOUSE_BOT_CONNECTION_STRING: postgresql+psycopg2://postgres:@/inhouse_bot

      # You need to put your Discord Bot token here
      INHOUSE_BOT_TOKEN: Nzg1OTQxMTA5Nzc1Nzk0MjI3.X8_Ksg.Kk4SbVI7xzNnVtFalVyosDUgih8

      # Those emoji help the bot look good and are defined with discord.py emoji syntax
      INHOUSE_BOT_TOP_EMOJI: '<:Top:787168203716427806>'
      INHOUSE_BOT_JGL_EMOJI: '<:jgl:787168231600816129>'
      INHOUSE_BOT_MID_EMOJI: '<:mid:787168231608680448>'
      INHOUSE_BOT_BOT_EMOJI: '<:bot:787168231337099285>'
      INHOUSE_BOT_SUP_EMOJI: '<:sup:787168203347591169>'

    volumes:
      # Socket volume to connect to the database
      - type: volume
        source: dbsocket
        target: /var/run/postgresql

    depends_on:
      - db

  # Database service for the bot
  db:
    image: postgres:alpine
    volumes:
      # Database persistence volume
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
      # Socket volume to communicate faster
      - type: volume
        source: dbsocket
        target: /var/run/postgresql
    environment:
      # CHANGE THE PASSWORD BEFORE DEPLOYMENT
      POSTGRES_PASSWORD: inhousebot
      POSTGRES_DB: inhouse_bot

  # Simple database management tool (will use the password you set for the db service)
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080


volumes:
  pgdata:     # Persistent data volume for the database
  dbsocket:   # Socket mounting volume
